### ISSUE TITLE
Unable to spin up react app:

### ISSUE THREAD

**Issue by jamie29w** [clearcapital/react-eval-project#1]
Hi CC Team,

I was unable to spin up a react app using the `create-react-app my-app --scripts-version cc-react-scripts` command due to the error below. I've also tried replacing `my-app` with `github-data-visualization`. Both yield the same error:

```
Aborting installation.
Unexpected error. Please report it as a bug:
TypeError: Cannot read property 'concat' of undefined
    at module.exports (/Users/AJWoodmancy/dev/my-app/node_modules/cc-react-scripts/scripts/init.js:144:22)
    at getPackageName.then.then.then.packageName (/Users/AJWoodmancy/.nvm/versions/node/v6.11.3/lib/node_modules/create-react-app/createReactApp.js:294:7)
    at process._tickCallback (internal/process/next_tick.js:109:7)

Deleting generated file... node_modules
Deleting generated file... package.json
Done.
```

Full command line is [attached](https://github.com/clearcapital/react-eval-project/files/1636573/module.exports.error.pdf) for reference.

**Comment by jordanpapaleo** [comment]
Do you use Yarn?

**Comment by jamie29w** [comment]
Yessir


On January 16, 2018 at 12:36:18 PM, Jordan Papaleo (notifications@github.com)
wrote:

Do you use Yarn?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/clearcapital/react-eval-project/issues/1#issuecomment-358096739>,
or mute the thread

**Comment by jordanpapaleo** [comment]
We do not use Yarn and there is an issue with our script and Yarn.  I know this is a big ask, but until we figure out the problem, could you try a global uninstall of yarn, then re run the script?

**Comment by jordanpapaleo** [comment]
We will try to get yarn support asap.

**Comment by jamie29w** [comment]
Thanks Jordan!

I’m hesitant to uninstall Yarn, since all of my portfolio projects rely
upon it. They’re all deployed, but I keep up on them and update from time
to time. I’ve been looking at other options too. Do you have an ETA so I
can prioritize?



On January 16, 2018 at 1:32:09 PM, Jordan Papaleo (notifications@github.com)
wrote:

We will try to get yarn support asap.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/clearcapital/react-eval-project/issues/1#issuecomment-358113474>,
or mute the thread

**Comment by jordanpapaleo** [comment]
We should have a PR in this evening.  Thank you for your patience. I know your time is valuable.

**Comment by jamie29w** [comment]
You rock! Thanks Jordan.

**Comment by jordanpapaleo** [comment]
Just merged a PR for the yarn fix.  Please take a look and then close if the issue is resolved.

**Comment by jamie29w** [comment]
I tried again this morning but am still getting the same error:

```
Aborting installation.
Unexpected error. Please report it as a bug:
TypeError: Cannot read property 'concat' of undefined
    at module.exports (/Users/AJWoodmancy/dev/github-data-visualization/node_modules/cc-react-scripts/scripts/init.js:144:22)
    at getPackageName.then.then.then.packageName (/Users/AJWoodmancy/.nvm/versions/node/v6.11.3/lib/node_modules/create-react-app/createReactApp.js:294:7)
    at process._tickCallback (internal/process/next_tick.js:109:7)

Deleting generated file... node_modules
Deleting generated file... package.json
Done.
```

**Comment by jordanpapaleo** [comment]
So we do not use yarn here.

You may just have to use create-react-app and roll your own redux.

**Comment by jamie29w** [comment]
Thanks Jordan. Will do.

**Comment by jonlu** [comment]
Hey Jamie, I made a fix to this in the code, but forgot to publish the update to npm. Can you try one last time? Should be working now. Thanks!

**Comment by Frankcarvajal** [comment]
Hey Jlu, I have confirmed that it is working now.

**Comment by jamie29w** [comment]
Confirmed, yarn is working now. Thanks all!
